# Generated by Django 2.0.1 on 2018-01-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('released_year', models.IntegerField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('is_adult', models.BooleanField(default=True)),
                ('imdb_id', models.CharField(max_length=256)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('imdb_num_votes', models.IntegerField(null=True)),
                ('genres', models.ManyToManyField(to='app.Genre')),
            ],
        ),
    ]
