# Generated by Django 2.0.1 on 2018-01-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_trailer_key',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
