# Generated by Django 2.0.1 on 2018-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_tmdb_id_and_youtube_trailer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
