# Generated by Django 2.0.1 on 2018-03-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_more_tmdb_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='in_netflix',
            field=models.BooleanField(default=False),
        ),
    ]
